# Generated by Django 5.1.1 on 2024-10-03 14:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_post_dhimcq', max_length=255, verbose_name='image'),
        ),
    ]
